# Generated by Django 4.2.11 on 2024-07-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_urunler_bedenler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urunler',
            name='bedenler',
        ),
        migrations.AddField(
            model_name='beden',
            name='durum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beden',
            name='urun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bedenler', to='myapp.urunler'),
        ),
    ]
